CREATE TABLE IF NOT EXISTS Inventory
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Price TEXT NOT NULL,
    Quantity INTEGER NOT NULL,
    AddedOn TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Account
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Money TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AccountData
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PersonName TEXT NOT NULL,
    TotalCash TEXT NOT NULL
);